version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_clubfit
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 311002
      POSTGRES_DB: clubfitdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./BackEnd
    container_name: clubfit_backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ./BackEnd:/app
    env_file:
      - ./BackEnd/.env
    command: sh -c "npx prisma migrate deploy && npm run dev"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_clubfit
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@clubfit.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data:
